### ISSUE TITLE
Expand/Collapse evolution does nothing, console warning

### ISSUE THREAD

**Issue by PoetikDragon** [madcowfred/padherder-issues#125]
I am not sure what expand/collapse evolution is supposed to do. Clicking on either link does nothing. The first time I click one of the links, this warning appears in the developer console:

event.returnValue is deprecated. Please use the standard event.preventDefault() instead. jquery.js:5374

Windows 8.1
Chrome 31.0.1650.63 m

**Comment by theinfra** [comment]
It's supposed to expand the evolutions of monsters who have another evolution after the one that's supposed to be next.

Like for example, I have a Shardra who's next evolution is a Shardran. In the Evolution column it shows this, along with the materials needed for the evo. But this Shardran then evolves into a Megalodran, which in turn ulti-evos into Drilling Shark Dragon, Megalodran. So if I click the "Expand evolutions" link, it'll expand all these evolutions into new lines so I know if I have the materials needed for the whole evolution chain. Collapse obviously collapses this.

As you may have already noticed, the link wouldn't do anything if all monsters in your monster box are at the last evolution or just one step before the last one because there's nothing to expand

**Comment by madcowfred** [comment]
^ what this person said.

The Chrome deprecation warning is a random change the Chrome team decided to make, it will be fixed when jQuery 1.11.0 final is released.
