### ISSUE TITLE
BAO Robin & BAO Copperhead IDs

### ISSUE THREAD

**Issue by SingedKitty** [madcowfred/padherder-issues#165]
I know this won't make you happy but there still seem to be problems with the Batman Collab. I'm US user (group B not that it matters). 

BAO Copperhead ID in-game is 928--you have 1928.
BAO Robin in-game is 673--you have 928.  
BAO Batman+S. Gloves is 675--you have 930.
BAO Solomon Grundy is 926--you have 1926.
BAO Catwoman is 671--you have 926.
BAO Firefly is 924--you have 1924.

I know you made some of these changes due to a reported issue so I hope there aren't different US versions? What a mess. Let me know if you need screenshots of these mobs.

**Comment by madcowfred** [comment]
This is actually a slightly different problem to the other BAO collab disasters. Monsters on PADherder use the wiki ID. The English wiki tries to stay largely in sync with the Chinese (I think) wiki (which is about the Japanese game). GungHo did a very mean thing and used the same IDs for different monsters in different regions :|

Not sure what the fix is going to be here - possibly use "#926US" etc as the displayed ID when adding/showing monsters, I haven't really decided on a good solution.

**Comment by SingedKitty** [comment]
Ahhh. How bizzare they'd do that. Can't make it easier on them either. 

Thought this might be why you were having trouble with links to padx so thought I'd mention it. Good luck with the cleanup. :) I'll go back to ignoring the IDs lol.

**Comment by sunglassesmichael** [comment]
I don't know if this is possible, but PDX added a zero to the end of the number, rather than a 1 to the front. This seems like a wiser choice to me, because it seems entirely possible that we could pass the numbers chosen by the wiki within the year, while 9260, for instance, would be a much more distant problem.

**Comment by madcowfred** [comment]
Finally put in a proper solution for this mess.
