### ISSUE TITLE
Downstream mats

### ISSUE THREAD

**Issue by lpfabulous** [madcowfred/padherder-issues#18]
Is there any way to implement a function so that, if you put a low-tier monster in, the system will track all the mats you need to get it to final tier? For instance, I have a Cupid, and it knows what I need to get to Angel, but I'd like it to also record what I need to get to Archangel after that.

**Comment by madcowfred** [comment]
The technical part of this should be easy enough, I'm just unsure how to effectively display this in the UI. Making the monsters table wider is something I'm not a fan of as it's already quite unwieldy.

**Comment by Dakiton** [comment]
You could make it be a link in the bottom right ("Advanced Evos") sort of thing.  When clicked it slides down and puts in the evos that are downstream from the current evo.  Not sure how to handle the multi different evos though.

**Comment by madcowfred** [comment]
Well, the first step would be to allow you to pick from the final evolutions for a monster instead of just the next one. Showing the future evolutions is the interesting part, if I could find somewhere to put an expand button (replace the <-- maybe?) it could just expand to be:

[Angel] \/ [1] [2] [3] [4] [5]
[Archangel <-- [1] [2] [3] [4] [5]

... or something. Still thinking about it!

**Comment by madcowfred** [comment]
Finally implemented this.
