### ISSUE TITLE
Registered but never got an email to activate

### ISSUE THREAD

**Issue by chonyi** [madcowfred/padherder-issues#234]
I registered for the website twice (username makezu then c.honyi) but never got an email to activate my account. I tried signing in with my login details - didn't work. Tried doing forgot password - didn't work. But if I register again, I see that my username is taken so that means my previous attempts worked but I just couldn't get the activation email. I've checked my spam and everything and I just never got the email.

**Comment by madcowfred** [comment]
Hm. I've had a few reports of issues with Microsoft email addresses, not sure what the deal is since all I can see in my mail log is the hotmail.com server accepting the email :( I've manually activated your 'makezu' account for now.

I think I'll just make email addresses optional for registering - you won't get automatic Disqus logins and Gravatar support until it's verified, but the account will be usable. Leaving this issue open to remind me to do so.

**Comment by bichen** [comment]
I had the same problem.  Tried signing up yesterday and did the exact things chonyi did.  Didn't get the activation email, tried getting a forgotten password and it said it sent but got nothing.  And yes, I am using a hotmail email address.  I forgot what username I was using.  Either bichen or spacemanspork.

**Comment by madcowfred** [comment]
I've rewritten the auth system to a) involve less steps, and b) not require email verification to get started. Any in-progress accounts were deleted, you should be able to make a new bichen account now.
