### ISSUE TITLE
API: target_evolution number looks incorrect

### ISSUE THREAD

**Issue by Serilyn** [madcowfred/padherder-issues#272]
target_evolution in the API docs says it should be the id of a monster in the monster's evolution chain. I would expect for a monster ID like 225(Valkyrie) to have a target of 694(Warrior Rose Valkyrie) however if you look at my valkyrie at http://www.padherder.com/user-api/monster/542318/ This doesn't seem to be the case. There, it is listed as 320(Dark Golem Mk III). I can't figure out what 320 would mean in this context. None of my other monsters have target_evolutions that make sense either.

**Comment by madcowfred** [comment]
Oof, this was a tricky one due to the way things are structured internally - 320 is the unique ID of that evolution. I've rewritten how this part works:
- The "target_evolution" field will now accept and return monster IDs like it claims to
- A missing "target_evolution" field is assumed to be "pick the first evolution on the end of this monster's evolution chain", ie what the 'Add monster' form defaults to.
- A "target_evolution" value of 0 is the same as choosing -NONE- for an evolution.
