### ISSUE TITLE
API call broke my monster box

### ISSUE THREAD

**Issue by Serilyn** [madcowfred/padherder-issues#407]
my monster box: https://www.padherder.com/user/Serilyn/monsters/ doesn't show any monsters. I've been writing a little helper tool and just added a way to evo my monsters from it. It seemed to be working, but last night I evolved my Raphael to Light Dominion Raphael  and now my monster box crashes before it shows my monsters.

Background to possible issue. API was sending back errors whenever I tried to set the target_evolution to null (or anything else) when I reached the top of the evo chain on my test ultimate archangel (#1103). Since I couldn't change the target_evolution it was saying that she was still targeting 1103 and showing the rainbow of 'lits to un-evo her if I viewed her in padherder. The difference this time is that Raphael has no ultimate yet so I'm guessing that #627 targeting #627 is what messed it up. 

The Raphael in question: https://www.padherder.com/user-api/monster/1090355/

**Comment by madcowfred** [comment]
Looks like the target_evolution field had two different issues, I think I've fixed them now. I've also manually fixed your monster, hopefully that doesn't happen again.
- It was being very weird about people daring to supply integers instead of a number string.
- The null handling was doing weird things when monsters were already ultimate evolved.

**Note**: setting target_evolution to null probably won't do what you expect - it will actually auto-select the first ultimate evolution (by ID) for obscure reasons. You need to set it to 0 (zero) to set it to nothing... unless the monster is already ultimate evolved in which case null will also set it to nothing. The code for the target_evolution field is terrifying :ghost:
