### ISSUE TITLE
Possible bug, strange behavior with multiple ult-evos in sets

### ISSUE THREAD

**Issue by zably** [madcowfred/padherder-issues#612]
It seems that "My Sets" only pays attention to the most recent ult-evo for gods that have multiple ult-evos when counting skills and awakenings.

Seen in this screenshot

![image](https://cloud.githubusercontent.com/assets/7295661/6651782/dcf99ff4-ca2a-11e4-83d0-b2a67916b2a0.png)

Underlord Inferno Hades 397 is max skilled, but isn't lighting up the trophy (Awoken Hades 1748 does, however).

Similarly, I have all 5 gods in "Japanese Gods 1" max awoken, and each are in a "final" ult-evo, but the star isn't lighting up (the tooltip actually says that only 2/5 are fully awoken).  If I switch Orochi, Susano, and Amaterasu to their other ult-evo, the awakenings count and I get the green star.

Is this on purpose?  I can see how some ult-evo's are better than others, it just seems like non-obvious behavior.

**Comment by madcowfred** [comment]
Nope, that's probably a bug. Thanks for the in-depth expalantion, it should help me track it down.

**Comment by madcowfred** [comment]
The Hades problem is due to some strange logic with how My Sets checks max skills (different skill on 1748 breaks things), I'll need to dig into the twisty passages of code later to work out how to fix it. The other one looks to be related - it's comparing the awakening count to the number of awakenings available to the last ultimate evo. Blarg!

**Comment by madcowfred** [comment]
Closing in favour of #806
