### ISSUE TITLE
More sort options in My Monsters

### ISSUE THREAD

**Issue by incrediblehulf** [madcowfred/padherder-issues#63]
Right now the only available sort is the default (by priority, then att, etc.). It would be nice to be able to click the columns to be able to sort ascending or descending by that column's value.

**Comment by Midnight08** [comment]
Heavily agree on this. With collections in the hundreds it is extremely difficult to manage things when we are unable to sort as needed.

**Comment by madcowfred** [comment]
I'll add some better sort options as part of an upcoming My Monsters filter revamp.

**Comment by PoetikDragon** [comment]
I came here just to make this request! We seriously need sortable headers for the table. It was the very first thing I noticed.

**Comment by iscribble** [comment]
I went ahead and created a bookmarklet to accomplish exactly this. Read about it here: http://www.reddit.com/r/PuzzleAndDragons/comments/1vblwf/padherder_monster_box_sorting/

@madcowfred I sent you an email yesterday, LMK if you'd like a copy of the uncompressed script :-)

**Comment by theinfra** [comment]
The issue here is not that we have little options to sort, but there aren't any whatsoever! :P What we have are _filters_, not _sorts_ XD

BUt seriously, I would be also interested in this. I'm using iscribble's bookmarklets in the meantime which work wonders, but a native way would be awesome.

If this is implemented, what I would also like to request, is to add three columns to the table, with the actual ATK/HP/RCV of the monster so we can use the sorting along with the filter, like getting a list of all my Red monsters, sorted by RCV, or all High Priorities, sorted by xp needed, etc.

**Comment by madcowfred** [comment]
More columns is fairly unlikely - the monsters page is already ~1175px wide to be usable, adding 3 new columns isn't going to help with that :worried:

**Comment by madcowfred** [comment]
First pass at a filters/sorting revamp is done, click the Show button next to the "Sorting: Default" text to see the sort box.

Screenshot: http://i.imgur.com/8xr19NA.png
