### ISSUE TITLE
yet another batman bug (robin)

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#762]
just noticed robin + e.stick's picture is ivy.

**Comment by Meldarion** [comment]
Taking a quick look, the problem seems to be across many of the Batman cards and even some of the Shinrabansho cards:
Exiled Apollo is using the pic for Joker
Joker is using the pic for Firefly
Catwoman is using the pic for Solomon Grundy
Robin is using the pic for Copperhead (NOT Poison Ivy)
The Batmen cards are using the pics for Bane, Deathstroke, and Exiled Apollo
Bane is using the pic for Kaguya
Sacred Dragon King Saiga is using the pic for Catwoman

The evolved forms of these cards are also using the pics of the evolved forms of what I listed above
And these are just the ones I see from the Sets and My Monsters tabs...

**Comment by Meldarion** [comment]
Ultimate Evolutions seem to be unaffected (at least from what I can see)

**Comment by madcowfred** [comment]
Yeah, I updated all of the monster images and forgot to add some code to account for the idiotic BAO mess. Fixed now.
