### ISSUE TITLE
Problem in Kirin evolution chain

### ISSUE THREAD

**Issue by chayashida** [madcowfred/padherder-issues#776]
Hi,

I noticed there was a problem evolving #1218 Kirin of the Sacred Gleam [L/L].
#2077 Green Gleaming Star Kirin, Sakuya [L/G] isn't available from her drop-down menu.

Also, when trying to set up the Evo for #751 Incarnation of Kirin, Sakuya to be #2077, the following error message is displayed on the dialog box to the left of the Cancel button:

Error: 400 {"target_evolution": ["Invalid target_evolution for this monster"]}

Let me know if you need more information. (I already has a workaround for the problem by deleting and re-adding the monster).

Thanks for a great site!

**Comment by madcowfred** [comment]
Yeah, I know something is very screwy with Kirin. I hope to have some time to look into it this weekend :(

**Comment by iNeedMoreAccounts** [comment]
Kirin's evolution chain isn't like most monsters.  The base form (751) evolves into #752.  Then #752 can branch into #1218 or #2389.  #1218 can further evolve into #2077.

I just changed my Green Star Kirin (#2077) to the new Awoken Sakuya (#2389) and I had to reverse evolve it twice.  I can't recall ever having to do that for any monster ever since I started playing pad.  I think with most monsters all three 'ultimate evolutions' would branch from #752.

**Comment by theinfra** [comment]
Bump, this issue is stil happening.

 I know it's been weeks since last activity here and since September with the latest new article, but this is a great tool that sadly needs a lot of fiddling to keep up to date or else it's gonna fall into obscurity :C

**Comment by madcowfred** [comment]
I've reworked how evolutions are verified in the API, it now just does a basic graph traversal check to see if the target is reachable from the monster. The old method for finding an evolution chain scares me and is the most fragile part of the code, I hate having to touch it :(
