### ISSUE TITLE
Chrome not displaying alternate evolutions when more than one are available.

### ISSUE THREAD

**Issue by Madnapali** [madcowfred/padherder-issues#814]
As subject says. This is working fine in other browsers as confirmed by myself and a few friends. 

It also seems like some monsters (Hino Kagutsuchi) are displaying only one, even when not in Chrome and I try to expand the list.

Chrome is current, AdBlock Plus is installed but I doubt that has anything to do with it.

**Comment by zably** [comment]
Regarding the second part, you said:

"AdBlock Plus is installed but I doubt that has anything to do with it."

I haven't used the mobile version of chrome at all, but on the desktop version, Adblock prevents several of the images from loading (usually because the images have random names, and some of them hit the "*fb.jpg" filter to prevent facebook ads).  If the missing monsters aren't duplicates, but actually different evo versions, it could just be a display issue due to white placeholder images loading instead of portraits.

**Comment by Madnapali** [comment]
I disabled ABP on the site, didn't seem to do the trick. ABP isn't blocking
anything, anyway.

Grabbed Firefox, and seeing the same issue. I guess this isn't a browser
problem but that most of my monsters have uvos so new that the site doesn't
have them listed, lol. Hino, as mentioned earlier, is only showing the
fire/light version. Meanwhile, my tier1 Dkali expands up to the uvo.

Guess you can close this out and I'll just muddle through it until you have
a chance to update it. Not that I know anything about API or the inner
workings of this game, but if there is anything I can do to help, I will
certainly do my best.

**Comment by sickcat99** [comment]
Hino is showing correctly for me in Chrome 46.024... I am updating to the latest and reply only if I see the bug

**Comment by Madnapali** [comment]
I figured it out, totally my fault. Weird that others saw this problem and
only in chrome but probably the same idiot mistake I made, lol.

Basically I for some reason thought that expanding the evo tree showed them
all. What I wanted to see was updating the evo of choice in the edit menu.
I use padlistener so I had no clue it was there. Just today started looking
through options and found it.

Sorry, I am a jackass. You can close this out and I'll educate the others
lol.

**Comment by Raijinili** [comment]
You and Fred are the only ones who can close it.
