### ISSUE TITLE
Incorrect XP for some monsters

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#962]
Some monsters which are currently at level 1 display a "Need XP" value of 1, and colored green as if the goal had been reached.

I've confirmed this so far for Deighk and Achtros. (Curiously, both are from Legendary Sea of Stars -- a relatively recent addition.)

![issue962_needxp1_deighk](https://cloud.githubusercontent.com/assets/1418951/19415083/fa12dac0-9318-11e6-8f42-1418a0ece11c.png)
![issue962_needxp1_achtros](https://cloud.githubusercontent.com/assets/1418951/19415084/ff1061fa-9318-11e6-96a0-9099dbf7a934.png)

Expected: Need about 8,888,888 XP.

**Comment by zedekblue** [comment]
Also an issue with 3066, 3067, 3160, 3161, & 3195, aka all the Pepper variants.

It's just an problem with the new XP curves. 3011 & 3012 have a max xp of 8 888 888, and the Peppers have a max of 1 154 448.

Technically unrelated but I believe this issue is also preventing padherder_proxy from working correctly. As someone with a 1000+ card box, I can't actually use padherder until this issue is fixed.

**Comment by madcowfred** [comment]
This should be fixed now - what sort of nutter makes a 1,154,448 XP curve?
